apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: gha-runner-scale-set-controller
  repo: oci://ghcr.io/actions/actions-runner-controller-charts
  version: 0.13.0
  namespace: devops-tools
- name: gha-runner-scale-set
  repo: oci://ghcr.io/actions/actions-runner-controller-charts
  version: 0.13.0
  namespace: devops-tools
  valuesFile: values.yaml
  