githubConfigUrl: https://github.com/home-kops

githubConfigSecret:
  github_app_id: <path:secret/data/devopstools/arc#githubAppId>
  github_app_installation_id: <path:secret/data/devopstools/arc#githubAppInstallationId>
  github_app_private_key: <path:secret/data/devopstools/arc/githubAppPrivateKey#private_key>

runnerScaleSetName: gha-scale-set

controllerServiceAccount:
  namespace: devops-tools
  name: gha-scale-set-controller-gha-rs-controller

minRunners: 1
