apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: jenkins
  repo: https://charts.jenkins.io
  version: 5.8.62
  releaseName: jenkins
  namespace: devops-tools
  valuesFile: values.yaml
