controller:
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  nodeSelector:
    size: m
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hostName: ci.<path:secret/data/infra#domain>
  cloudName: "kubernetes"
  numExecutors: 0
  javaOpts: "-Djenkins.install.runSetupWizard=false"
  jenkinsUrl: https://ci.<path:secret/data/infra#domain>/
  additionalPlugins:
  - job-dsl:1.93
#  - dark-theme:567.v9d3ca_a_3142f5
  - locale:587.v7b_843928a_719
  JCasC:
    defaultConfig: true
    configScripts:
      jenkins: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: admin
                  password: <path:secret/data/devopstools/jenkins#admin_password>
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false
          clouds:
            - kubernetes:
                name: "kubernetes"
                serverUrl: "https://192.168.1.50:6443"
                namespace: "devops-tools"
                webSocket: true
                templates:
                  - name: "agent-s"
                    label: "agent-s"
                    serviceAccount: "jenkins-admin"
                    containers:
                      - name: "jnlp"
                        image: "msd117/jenkins-generic-agent:0.0.1"
                        ttyEnabled: true
                        resourceRequestCpu: "100m"
                        resourceRequestMemory: "256Mi"
                        resourceLimitCpu: "200m"
                        resourceLimitMemory: "512Mi"
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: "github-home-kops-token"
                      username: "<path:secret/data/devopstools/jenkins#gh_org_username>"
                      password: "<path:secret/data/devopstools/jenkins#gh_org_token>"
#          themeManager:
#            disableUserThemes: true
#            theme: "darkSystem"
      appearance: |
        appearance:
          locale:
            systemLocale: en
            ignoreAcceptLanguage: true
      jobs: |
        jobs:
        - script: >
            def repos = [
              'k8s-devops-tools'
            ]

            repos.each { repoName ->
              multibranchPipelineJob(repoName) {
                branchSources {
                  branchSource {
                    source {
                      github {
                        id(repoName)
                        repoOwner('home-kops')
                        repository(repoName)
                        repositoryUrl("https://github.com/home-kops/${repoName}.git")
                        configuredByUrl(true)
                        credentialsId('github-home-kops-token')

                        traits {
                          gitHubBranchDiscovery {
                            strategyId(3)
                          }
                          gitHubPullRequestDiscovery {
                            strategyId(3)
                          }
                          headRegexFilterWithPR {
                            regex('^main$')
                            tagRegex('^(v[0-9]+\\.[0-9]+\\.[0-9]+)$')
                          }
                        }
                      }
                    }
                  }
                }

                triggers {
                  periodicFolderTrigger {
                    interval('5m')
                  }
                }

                orphanedItemStrategy {
                  discardOldItems {
                    numToKeep(3)
                  }
                }
              }
            }
persistence:
  enabled: true
  storageClass: nfs-sc
  size: 8Gi
