controller:
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  nodeSelector:
    size: m
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hostName: ci.<path:secret/data/infra#domain>
  cloudName: "kubernetes"
  numExecutors: 0
  javaOpts: "-Djenkins.install.runSetupWizard=false"
  jenkinsUrl: https://ci.<path:secret/data/infra#domain>/
  additionalPlugins:
  - job-dsl:1.93
#  - dark-theme:567.v9d3ca_a_3142f5
  - locale:587.v7b_843928a_719
  - github-branch-source:1822.v9eec8e5e69e3
  - scm-filter-branch-pr:222.v72301ecb_a_ee7
  JCasC:
    defaultConfig: true
    securityRealm: |-
      local:
        allowsSignup: false
        users:
        - id: admin
          password: <path:secret/data/devopstools/jenkins#admin_password>
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
    configScripts:
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: "github-home-kops-token"
                      username: "<path:secret/data/devopstools/jenkins#gh_org_username>"
                      password: "<path:secret/data/devopstools/jenkins#gh_org_token>"
#          themeManager:
#            disableUserThemes: true
#            theme: "darkSystem"
      appearance: |
        appearance:
          locale:
            systemLocale: en
            ignoreAcceptLanguage: true
      jobs: |
        jobs:
        - script: >
            def repos = [
              'k8s-devops-tools',
              'k8s-media',
              'k8s-monitoring',
              'k8s-network',
              'k8s-storage',
              'k8s-vault'
            ]

            repos.each { repoName ->
              multibranchPipelineJob(repoName) {
                branchSources {
                  branchSource {
                    source {
                      github {
                        id(repoName)
                        repoOwner('home-kops')
                        repository(repoName)
                        repositoryUrl("https://github.com/home-kops/${repoName}.git")
                        configuredByUrl(true)
                        credentialsId('github-home-kops-token')

                        traits {
                          gitHubBranchDiscovery {
                            strategyId(3)
                          }
                          gitHubPullRequestDiscovery {
                            strategyId(3)
                          }
                          headRegexFilterWithPR {
                            regex('^main$')
                            tagRegex('^(v[0-9]+\\.[0-9]+\\.[0-9]+)$')
                          }
                        }
                      }
                    }
                  }
                }

                triggers {
                  periodicFolderTrigger {
                    interval('5m')
                  }
                }

                orphanedItemStrategy {
                  discardOldItems {
                    numToKeep(3)
                  }
                }
              }
            }

agent:
  disableDefaultAgent: true
  podTemplates:
    agent-s: |
      - name: "agent-s"
        label: "agent-s"
        serviceAccount: "jenkins"
        containers:
          - name: "jnlp"
            image: "msd117/jenkins-generic-agent:0.0.1"
            ttyEnabled: true
            resourceRequestCpu: "100m"
            resourceRequestMemory: "256Mi"
            resourceLimitCpu: "200m"
            resourceLimitMemory: "512Mi"

persistence:
  enabled: true
  storageClass: nfs-sc
  size: 8Gi
